# The hermetic build for the platforms Nix runs on — Linux and macOS, never
# Windows, whose artefact is `x86_64-pc-windows-msvc` and whose linker Nix cannot
# pin (`.process/Roadmap.md` §J4; `docs/VERIFY.md` §4).
#
# What this buys over `cargo build --release --locked`: the compiler, the linker,
# the C toolchain `ring` needs, and every system library are named by
# `flake.lock`, so two machines holding the same lock produce the same bytes
# without either of them being told what to install. `nix build --rebuild` is
# then the reproducibility check — Nix builds a second time and refuses if the
# output differs from what is already in the store.
#
# The Rust version has one authority, `rust-toolchain.toml`; this file reads it
# rather than repeating it. Tests are not run here: CI runs `cargo test` on the
# same platforms already, and a test never reaches the artefact (`just boxes`).
#
# `flake.lock` is generated by the first machine that runs `nix flake lock` and
# committed beside this file. Until it is, the CI job below produces one as an
# artefact to be committed by hand.
{
  description = "kusanagi — agent communication that needs to trust no server";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    { self, nixpkgs, rust-overlay }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      each =
        f:
        nixpkgs.lib.genAttrs systems (
          system:
          f (import nixpkgs {
            inherit system;
            overlays = [ rust-overlay.overlays.default ];
          })
        );
      toolchainOf = pkgs: pkgs.rust-bin.fromRustupToolchainFile ./rust-toolchain.toml;
      manifest = (nixpkgs.lib.importTOML ./Cargo.toml).workspace.package;
    in
    {
      packages = each (
        pkgs:
        let
          toolchain = toolchainOf pkgs;
          platform = pkgs.makeRustPlatform {
            cargo = toolchain;
            rustc = toolchain;
          };
        in
        rec {
          kusanagi = platform.buildRustPackage {
            pname = "kusanagi";
            version = manifest.version;
            # The flake's own source is the git tree: only tracked files, so
            # nothing in `.process/`, `target/` or `dist/` can reach the build.
            src = self;
            cargoLock.lockFile = ./Cargo.lock;
            cargoBuildFlags = [ "--package" "kusanagi" ];
            doCheck = false;
            meta = {
              description = manifest.description or "agent communication that needs to trust no server";
              homepage = manifest.repository;
              license = pkgs.lib.licenses.mpl20;
              mainProgram = "kusanagi";
            };
          };
          default = kusanagi;
        }
      );

      # The same tools a contributor's machine has, for `just check`. `cabal`
      # is left out on purpose: `adversary/` is outside the workspace and skips
      # itself when GHC is absent (`justfile`).
      devShells = each (pkgs: {
        default = pkgs.mkShell {
          packages = [
            (toolchainOf pkgs)
            pkgs.just
            pkgs.cargo-deny
          ];
        };
      });

      formatter = each (pkgs: pkgs.nixfmt-rfc-style);
    };
}
